args <- commandArgs(trailingOnly = TRUE)
group <- eval(parse(text=args[1]))
d <- readRDS("C:/xampp/htdocs/prot/uploads/boxplot2.rds")
#f1 <- (d[,1])
#fn <- (d[length(d)])
data.m <- as.matrix(d)
saveRDS(data.m, "C:/xampp/htdocs/prot/uploads/norm.rds")
quan <- c()
for (i in 1:dim(data.m)[2])
{
	tmp.q <- quantile(data.m[,i],0.75)
	quan <- c(quan,tmp.q)
}
repe <- max(table(group))
maxi <- max(group)
library(RColorBrewer)
cols <- brewer.pal(maxi,"BuGn")
png("uploads/boxplot2.png")
boxplot(data.m, ylim=c(0,max(quan)),las=2, col=rep(c(cols),each = repe))
dev.off()
