args <- commandArgs(trailingOnly = TRUE)
d <- readRDS("C:/xampp/htdocs/prot/uploads/norm.rds")
group <- eval(parse(text=args[1]))
repe <- max(table(group))
maxi <- max(group)
library(BBmisc)
a <- normalize(d, method = "center", margin = 2, on.constant = "quiet")
data_f <- data.frame(a)
library(WriteXLS)
WriteXLS(data_f, ExcelFileName = "C:/xampp/htdocs/prot/uploads/data.xlsx",AdjWidth = T, )
saveRDS(data_f, "C:/xampp/htdocs/prot/uploads/normal.rds")
quan <- c()
for (i in 1:dim(a)[2])
{
	tmp.q <- quantile(a[,i],1.0)
	quan <- c(quan,tmp.q)
}
library(RColorBrewer)
cols <- brewer.pal(maxi,"BuGn")
png("uploads/boxplotmean.png")
boxplot(a, ylim=c(0,max(quan)),las=2, col=rep(c(cols),each = repe))
dev.off()
