args <- commandArgs(trailingOnly = TRUE)
d <- readRDS("C:/xampp/htdocs/prot/uploads/norm.rds")
group <- eval(parse(text=args[1]))
library (qsmooth)
repe <- max(table(group))
maxi <- max(group)
group_factor <- rep(c(group),each=repe)
qs <- qsmooth(object = d, group_factor = group_factor)
qs.data <- qsmoothData(qs)
#data_f <- data.frame(qs.data)
library(WriteXLS)
WriteXLS(qs.data, ExcelFileName = "C:/xampp/htdocs/prot/uploads/data.xlsx",AdjWidth = T, )
saveRDS(qs.data, "C:/xampp/htdocs/prot/uploads/normal.rds")
quan <- c()
for (i in 1:dim(qs.data)[2])
{
	tmp.q <- quantile(qs.data[,i],0.75)
	quan <- c(quan,tmp.q)
}
library(RColorBrewer)
cols <- brewer.pal(maxi,"BuGn")
png("uploads/boxplotqs.png")
boxplot(qs.data, ylim=c(0,max(quan)),las=2, col=rep(c(cols),each = repe))
dev.off()