args <- commandArgs(trailingOnly = TRUE)
d <- readRDS("C:/xampp/htdocs/prot/uploads/norm.rds")
group <- eval(parse(text=args[1]))
library (preprocessCore)
a <- normalize.quantiles(d)
data_f <- data.frame(a)
library(WriteXLS)
WriteXLS(data_f, ExcelFileName = "C:/xampp/htdocs/prot/uploads/data.xlsx",AdjWidth = T, )
saveRDS(data_f, "C:/xampp/htdocs/prot/uploads/normal.rds")
quan <- c()
for (i in 1:dim(a)[2])
{
	tmp.q <- quantile(a[,i],0.75)
	quan <- c(quan,tmp.q)
}
repe <- max(table(group))
maxi <- max(group)
library(RColorBrewer)
cols <- brewer.pal(maxi,"BuGn")
png("uploads/boxplotqn.png")
boxplot(a, ylim=c(0,max(quan)),las=2, col=rep(c(cols),each = repe))
dev.off()